# Generated by Django 5.0.4 on 2026-03-22 23:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJobModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_user_id', models.UUIDField()),
                ('report_type', models.CharField(max_length=120)),
                ('format_label', models.CharField(blank=True, max_length=40, null=True)),
                ('parameter_summary', models.TextField(blank=True, max_length=1000, null=True)),
                ('source_metric_names', models.JSONField(default=list)),
                ('generated_artifact_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('retention_label', models.CharField(blank=True, max_length=60, null=True)),
                ('status_label', models.CharField(default='queued', max_length=20)),
                ('requested_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_job',
                'ordering': ['-requested_at'],
            },
        ),
    ]
