# Generated by Django 5.0.4 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportjobmodel',
            name='reports_job_status_label_valid',
        ),
    ]
