# Generated by Django 5.0.4 on 2026-03-22 21:47

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal_user_id', models.UUIDField(db_index=True)),
                ('session_scope_label', models.CharField(max_length=80)),
                ('role_labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('auth_method_label', models.CharField(blank=True, default='', max_length=40)),
                ('mfa_required', models.BooleanField(default=False)),
                ('mfa_satisfied', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_hash', models.CharField(blank=True, default='', max_length=128)),
                ('refresh_token_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'identity_access_auth_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserRoleBindingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('role_label', models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Coordinator'), ('coach', 'Coach'), ('athlete', 'Athlete'), ('member', 'Member')], max_length=40)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'identity_access_user_role_bindings',
                'unique_together': {('user_id', 'role_label')},
            },
        ),
    ]
