# Generated by Django 5.0.4 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_access', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrolebindingmodel',
            name='identity_access_role_binding_role_label_valid',
        ),
        migrations.RemoveIndex(
            model_name='authsessionmodel',
            name='ia_session_revoked_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='authsessionmodel',
            name='ia_session_refresh_token_idx',
        ),
        migrations.RemoveIndex(
            model_name='authsessionmodel',
            name='ia_session_revoked_user_idx',
        ),
    ]
