# Generated by Django 5.0.4 on 2026-03-22 23:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeliveryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_user_id', models.UUIDField()),
                ('channel_label', models.CharField(max_length=40)),
                ('notification_template_ref', models.CharField(blank=True, max_length=160, null=True)),
                ('event_envelope_ref', models.CharField(blank=True, max_length=160, null=True)),
                ('preference_label', models.CharField(blank=True, max_length=40, null=True)),
                ('delivery_status_label', models.CharField(default='queued', max_length=40)),
                ('retry_count', models.IntegerField(default=0)),
                ('requested_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification_delivery',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreferencesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(unique=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.CharField(blank=True, max_length=5, null=True)),
                ('quiet_hours_end', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'user_notification_preferences',
            },
        ),
    ]
