# Generated by Django 5.0.4 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationdeliverymodel',
            name='notifications_delivery_status_label_valid',
        ),
        migrations.RemoveConstraint(
            model_name='notificationdeliverymodel',
            name='notifications_delivery_retry_count_non_negative',
        ),
    ]
