# Generated by Django 5.0.4 on 2026-03-22 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=20)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by_user_id', models.UUIDField(db_index=True)),
                ('current_version_id', models.UUIDField(blank=True, null=True)),
                ('visibility_mode', models.CharField(default='RESTRICTED', max_length=20)),
                ('editorial_status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exercise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseACLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField()),
                ('created_by_user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercise_acl',
                'unique_together': {('exercise_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseRelationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_exercise_id', models.UUIDField(db_index=True)),
                ('to_exercise_id', models.UUIDField(db_index=True)),
                ('relation_type', models.CharField(max_length=30)),
                ('created_by_user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercise_relation',
                'unique_together': {('from_exercise_id', 'to_exercise_id', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseVersionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_id', models.UUIDField(db_index=True)),
                ('version_number', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('coaching_cues', models.CharField(blank=True, max_length=1000, null=True)),
                ('safety_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('session_phase', models.CharField(max_length=30)),
                ('primary_objective', models.CharField(max_length=30)),
                ('secondary_objective', models.CharField(blank=True, max_length=30, null=True)),
                ('game_phases', models.JSONField(default=list)),
                ('age_categories', models.JSONField(default=list)),
                ('skill_level', models.CharField(max_length=20)),
                ('complexity', models.IntegerField()),
                ('physical_load', models.CharField(max_length=20)),
                ('min_athletes', models.IntegerField()),
                ('max_athletes', models.IntegerField()),
                ('estimated_duration_minutes', models.IntegerField()),
                ('space_required', models.CharField(max_length=20)),
                ('materials', models.JSONField(default=list)),
                ('change_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercise_version',
                'ordering': ['exercise_id', '-version_number'],
                'unique_together': {('exercise_id', 'version_number')},
            },
        ),
    ]
