# Generated by Django 5.0.4 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercisemodel',
            name='exercises_exercise_scope_valid',
        ),
        migrations.RemoveConstraint(
            model_name='exercisemodel',
            name='exercises_exercise_visibility_mode_valid',
        ),
        migrations.RemoveConstraint(
            model_name='exercisemodel',
            name='exercises_exercise_editorial_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='exerciserelationmodel',
            name='exercises_relation_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseversionmodel',
            name='exercises_version_session_phase_valid',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseversionmodel',
            name='exercises_version_primary_objective_valid',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseversionmodel',
            name='exercises_version_physical_load_valid',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseversionmodel',
            name='exercises_version_space_required_valid',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseversionmodel',
            name='exercises_version_skill_level_valid',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseversionmodel',
            name='exercises_version_complexity_range',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseversionmodel',
            name='exercises_version_min_athletes_positive',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseversionmodel',
            name='exercises_version_max_athletes_cap',
        ),
    ]
