StylesPath = .github/styles
MinAlertLevel = warning
Vocab = HBTrack

# Mantenha os packages instalados (ok), mas NÃO use como base por enquanto.
Packages = https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip, https://github.com/errata-ai/Google/releases/latest/download/Google.zip

[docs/_canon/**/*.md]
BasedOnStyles = HBTrack

[docs/hbtrack/modulos/**/*.md]
BasedOnStyles = HBTrack