# Generated by Django 5.0.4 on 2026-03-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('sport_cycle_label', models.CharField(blank=True, max_length=80, null=True)),
                ('status_label', models.CharField(db_index=True, default='DRAFT', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('phase_labels', models.JSONField(default=list)),
                ('team_ids', models.JSONField(default=list)),
                ('competition_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seasons_season',
                'ordering': ['-start_date'],
            },
        ),
    ]
