# Generated by Django 5.0.4 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seasonmodel',
            name='seasons_season_start_lte_end',
        ),
        migrations.RemoveConstraint(
            model_name='seasonmodel',
            name='seasons_season_status_label_valid',
        ),
        migrations.RemoveIndex(
            model_name='seasonmodel',
            name='seasons_season_start_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='seasonmodel',
            name='seasons_season_org_status_idx',
        ),
    ]
