# Generated by Django 5.0.4 on 2026-03-22 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutEventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_id', models.UUIDField(db_index=True)),
                ('event_label', models.CharField(max_length=120)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('athlete_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('team_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('tag_labels', models.JSONField(default=list)),
                ('clip_asset_refs', models.JSONField(default=list)),
                ('coding_schema_label', models.CharField(blank=True, max_length=120, null=True)),
                ('tactical_aggregation_label', models.CharField(blank=True, max_length=120, null=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scout_event',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
