# Generated by Django 5.0.4 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scouteventmodel',
            name='scout_event_duration_ms_non_negative',
        ),
    ]
