"""compile_contracts.py — HB Track Contracts Compiler

Reads: docs/hbtrack/modulos/*/graph/openapi_paths.yaml  (SOURCE MASTER per module)
Validates: operation_ids in openapi_paths.yaml match endpoints.yaml
Generates: contracts/openapi/paths/<module>.yaml         (DERIVED — do not edit manually)

Usage:
    python3 scripts/compile/compile_contracts.py --all
    python3 scripts/compile/compile_contracts.py --module users
    python3 scripts/compile/compile_contracts.py --check   # validate only, no write
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent.parent

MODULES = [
    "ai_ingestion", "analytics", "audit", "competitions", "exercises",
    "identity_access", "matches", "medical", "notifications", "reports",
    "scout", "seasons", "teams", "training", "users", "video", "wellness",
]

GENERATED_HEADER_TEMPLATE = """\
# GENERATED by scripts/compile/compile_contracts.py — do not edit manually
# Source: docs/hbtrack/modulos/{module}/graph/openapi_paths.yaml
# To update: edit the source master above, then re-run compile_contracts.py
#
# Each path must belong exclusively to this module (LAYOUT §6).
# Naming conventions (api_rules.yaml canonical_conventions):
#   - path segments: kebab-case (no /api, no /v1)
#   - query params: camelCase
#   - JSON fields: camelCase
#   - OWASP API Security Top 10 (2023) compliance mandatory

"""


def _extract_path_content(source_text: str) -> str:
    """Strip the source-master comment header, return only YAML path content."""
    lines = source_text.splitlines(keepends=True)
    start = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            start = i
            break
    return "".join(lines[start:])


def _collect_operation_ids_from_paths(paths_content: str) -> set[str]:
    """Extract all operationId values from a paths YAML string."""
    try:
        data = yaml.safe_load(paths_content) or {}
    except yaml.YAMLError:
        return set()
    op_ids: set[str] = set()
    for path_item in data.values():
        if not isinstance(path_item, dict):
            continue
        for method in ("get", "post", "put", "patch", "delete", "head", "options"):
            op = path_item.get(method)
            if isinstance(op, dict) and "operationId" in op:
                op_ids.add(op["operationId"])
    return op_ids


def _collect_operation_ids_from_endpoints(module: str) -> set[str]:
    """Extract operationId values from endpoints.yaml for the given module."""
    ep_path = ROOT / "docs/hbtrack/modulos" / module / "graph" / "endpoints.yaml"
    if not ep_path.exists():
        return set()
    try:
        data = yaml.safe_load(ep_path.read_text()) or {}
    except yaml.YAMLError:
        return set()
    op_ids: set[str] = set()
    endpoints = data.get("endpoints", [])
    if isinstance(endpoints, list):
        for ep in endpoints:
            if isinstance(ep, dict) and "operation_id" in ep:
                op_ids.add(ep["operation_id"])
    return op_ids


def compile_module(module: str, check_only: bool = False) -> dict:
    """Compile a single module. Returns result dict."""
    source_path = ROOT / "docs/hbtrack/modulos" / module / "graph" / "openapi_paths.yaml"
    dest_path = ROOT / "contracts/openapi/paths" / f"{module}.yaml"

    if not source_path.exists():
        return {"module": module, "status": "ERROR", "error": f"source not found: {source_path}"}

    source_text = source_path.read_text()
    path_content = _extract_path_content(source_text)

    # Validate: parse YAML
    try:
        yaml.safe_load(path_content)
    except yaml.YAMLError as e:
        return {"module": module, "status": "ERROR", "error": f"invalid YAML: {e}"}

    # Validate: operation_id parity with endpoints.yaml
    path_op_ids = _collect_operation_ids_from_paths(path_content)
    ep_op_ids = _collect_operation_ids_from_endpoints(module)

    parity_warnings: list[str] = []
    if ep_op_ids:
        missing_in_paths = ep_op_ids - path_op_ids
        missing_in_endpoints = path_op_ids - ep_op_ids
        if missing_in_paths:
            parity_warnings.append(f"operationIds in endpoints.yaml not in openapi_paths: {missing_in_paths}")
        if missing_in_endpoints:
            parity_warnings.append(f"operationIds in openapi_paths not in endpoints.yaml: {missing_in_endpoints}")

    # Generate output
    generated = GENERATED_HEADER_TEMPLATE.format(module=module) + path_content

    if not check_only:
        dest_path.write_text(generated)

    return {
        "module": module,
        "status": "PASS",
        "check_only": check_only,
        "parity_warnings": parity_warnings,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="HB Track Contracts Compiler")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--all", action="store_true", help="Compile all 17 modules")
    group.add_argument("--module", metavar="MODULE", help="Compile a single module")
    group.add_argument("--check", action="store_true", help="Validate only — no file writes")
    args = parser.parse_args()

    check_only = args.check
    if args.module:
        modules_to_run = [args.module]
    else:
        modules_to_run = MODULES

    results = []
    errors = 0
    for mod in modules_to_run:
        result = compile_module(mod, check_only=check_only)
        results.append(result)
        status = result["status"]
        if status == "ERROR":
            errors += 1
            print(f"  ERROR [{mod}] {result['error']}")
        else:
            warnings = result.get("parity_warnings", [])
            warn_str = f" (warnings: {len(warnings)})" if warnings else ""
            action = "checked" if check_only else "compiled"
            print(f"  PASS  [{mod}] {action}{warn_str}")
            for w in warnings:
                print(f"        WARN: {w}")

    print()
    if errors:
        print(f"RESULT: FAIL — {errors}/{len(modules_to_run)} module(s) failed")
        return 1
    action_label = "Check" if check_only else "Compile"
    print(f"RESULT: PASS — {action_label} completed for {len(modules_to_run)} module(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
