"""Escreve _reports/ARQUITETO.yaml com PLAN_HANDOFF para AR_201."""
import os
os.chdir(r"c:\HB TRACK")

content = (
    "# ARQUITETO.yaml -- PLAN_HANDOFF para AR_201\n\n"
    "| Campo | Valor |\n"
    "|---|---|\n"
    "| **Protocolo** | v1.3.0 |\n"
    "| **Branch** | dev-changes-2 |\n"
    "| **HEAD** | b123a58 |\n"
    "| **Data** | 2026-03-02 |\n"
    "| **Status** | PLAN_HANDOFF -- AR_201 READY |\n"
    "| **gen_docs_ssot.py** | OpenAPI FAILED (backend offline, pre-existente) / Schema SQL OK / Alembic OK / Manifest OK |\n\n"
    "---\n\n"
    "## Contexto\n\n"
    "AR_200 foi executada pelo Executor: 10 testes rodados, 10 arquivos de evidencia criados, TEST_MATRIX v1.7.0 atualizada. "
    "Porem a validation_command original tem falso positivo: janela fixa de 450 chars a partir de `| INV-TRAIN-005` "
    "extravaza para INV-006 (NOT_RUN legitimo -- nao estava no top-10). Resultado: executor_main.log Exit Code: 1. "
    "Todos os ACs estao satisfeitos no arquivo. Plano AR_201 criado para corrigir o contrato.\n\n"
    "---\n\n"
    "## Planos Materializados\n\n"
    "| AR | Titulo | Plano JSON | Dependencia |\n"
    "|---|---|---|---|\n"
    "| AR_201 | Fix validation_command AR_200: janela 450 -> split-por-linha + re-executar hb report 200 | "
    "docs/_canon/planos/ar_201_fix_validation_command_ar200_window.json | AR_200 executada (evidencias OK) |\n\n"
    "---\n\n"
    "## Ordem de Execucao\n\n"
    "1. AR_201 (unica -- sequencial)\n\n"
    "---\n\n"
    "## Diagnostico por AR\n\n"
    "### AR_201 -- Fix validation_command AR_200\n\n"
    "**Write Scope**:\n"
    "- docs/hbtrack/ars/features/ (AR_200 file)\n"
    "- docs/hbtrack/evidence/AR_200/ (re-executar hb report 200)\n\n"
    "**Descricao do fix**:\n"
    "Substituir na validation_command de AR_200 a checagem via janela fixa:\n"
    "  `t.find(lbl)!=-1 and 'NOT_RUN' in t[t.find('| '+lbl):t.find('| '+lbl)+450]`\n"
    "por verificacao linha-a-linha:\n"
    "  `any('NOT_RUN' in ln for ln in t.split(chr(10)) if ln.startswith('| '+lbl+' '))`\n\n"
    "**Nova validation_command completa para AR_200** (substituicao total do bloco no arquivo):\n\n"
    "```\n"
    "python -c \"import os,sys; base='_reports/training'; ids=['INV-001','INV-002','INV-003','INV-004','INV-005','INV-008','INV-009','INV-030','INV-032','CONTRACT-077-085']; [sys.exit('FAIL: missing '+base+'/TEST-TRAIN-'+i+'.md') for i in ids if not os.path.exists(base+'/TEST-TRAIN-'+i+'.md')]; [sys.exit('FAIL: AR Origem ausente em '+base+'/TEST-TRAIN-'+i+'.md') for i in ids if 'AR Origem: AR_200' not in open(base+'/TEST-TRAIN-'+i+'.md',encoding='utf-8').read()]; t=open('docs/hbtrack/modulos/treinos/TEST_MATRIX_TRAINING.md',encoding='utf-8').read(); assert 'v1.7.0' in t,'FAIL: TEST_MATRIX nao bump para v1.7.0'; inv=[('001','INV-TRAIN-001'),('002','INV-TRAIN-002'),('003','INV-TRAIN-003'),('004','INV-TRAIN-004'),('005','INV-TRAIN-005'),('008','INV-TRAIN-008'),('009','INV-TRAIN-009'),('030','INV-TRAIN-030'),('032','INV-TRAIN-032')]; [sys.exit('FAIL: NOT_RUN persiste na linha '+lbl) for _,lbl in inv if any('NOT_RUN' in ln for ln in t.split(chr(10)) if ln.startswith('| '+lbl+' '))]; ct_ids=['CONTRACT-TRAIN-077','CONTRACT-TRAIN-078','CONTRACT-TRAIN-079','CONTRACT-TRAIN-080','CONTRACT-TRAIN-081','CONTRACT-TRAIN-082','CONTRACT-TRAIN-083','CONTRACT-TRAIN-084','CONTRACT-TRAIN-085']; [sys.exit('FAIL: NOT_RUN persiste na linha '+c) for c in ct_ids if any('NOT_RUN' in ln for ln in t.split(chr(10)) if ln.startswith('| '+c+' '))]; print('PASS: 10 evidencias criadas com AR_200 + TEST_MATRIX v1.7.0 + NOT_RUN removido')\"\n"
    "```\n\n"
    "**Validation Command de AR_201** (para hb report 201):\n\n"
    "```\n"
    "python -c \"import sys; ar200=open('docs/hbtrack/ars/features/AR_200_executar_top-10_testes_coberto+not_run_e_salvar_ev.md',encoding='utf-8').read(); assert '+450' not in ar200,'FAIL: janela 450 ainda presente em AR_200'; assert 'split' in ar200,'FAIL: split-por-linha ausente em AR_200'; log=open('docs/hbtrack/evidence/AR_200/executor_main.log',encoding='utf-8').read(); assert 'Exit Code: 0' in log,'FAIL: executor_main.log AR_200 nao tem Exit Code: 0'; assert 'PASS: 10 evidencias' in log,'FAIL: PASS ausente em executor_main.log'; print('PASS: AR_200 validation_command corrigida + executor_main.log Exit Code: 0')\"\n"
    "```\n\n"
    "**Criterios de Aceite**:\n"
    "- AC-001: AR_200 nao contem `+450` na validation_command\n"
    "- AC-002: AR_200 contem `split` na validation_command\n"
    "- AC-003: docs/hbtrack/evidence/AR_200/executor_main.log contem `Exit Code: 0`\n"
    "- AC-004: docs/hbtrack/evidence/AR_200/executor_main.log contem `PASS: 10 evidencias`\n\n"
    "**Passos para o Executor**:\n"
    "1. `hb plan docs/_canon/planos/ar_201_fix_validation_command_ar200_window.json`\n"
    "2. Editar secao `## Validation Command (Contrato)` em docs/hbtrack/ars/features/AR_200_*.md:\n"
    "   Substituir o bloco de codigo pela nova validation_command (acima)\n"
    "3. Re-executar `hb report 200` com a nova validation_command (deve retornar PASS + Exit Code: 0)\n"
    "4. Executar `hb report 201 <validation_command_ar201>` para gerar evidencia de AR_201\n\n"
    "**Riscos**:\n"
    "- hb report 200 exige cmd-match: o comando passado DEVE ser identico ao salvo no arquivo AR_200. "
    "Recomendar atualizar temp/_run_ar200_report.py com a nova validation_command.\n"
    "- A nova validation_command usa `ln.startswith('| '+lbl+' ')` (espaco apos ID) -- garante nao-match de prefixo.\n"
    "- Usar `chr(10)` ou `'\\n'` para o split (PowerShell pode ter problemas com escape de backslash).\n\n"
    "---\n\n"
    "## Resultado dry-run\n\n"
    "1 ARs seriam criados, 0 puladas. Todas as validacoes passaram.\n\n"
    "---\n\n"
    "## Nota para o Testador\n\n"
    "Apos o Executor concluir AR_201:\n"
    "- `hb verify 201` (triple-run, exit_code=0, hashes identicos)\n"
    "- `hb verify 200` (triple-run com executor_main.log regenerado Exit Code: 0)\n"
    "- hb seal 201 -> hb seal 200 (nesta ordem)\n"
)

with open("_reports/ARQUITETO.yaml", "w", encoding="utf-8") as f:
    f.write(content)
print("ARQUITETO.yaml written OK")
