# Generated by Django 5.0.4 on 2026-03-22 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('display_name', models.CharField(max_length=120)),
                ('role_label', models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Coordinator'), ('coach', 'Coach'), ('athlete', 'Athlete'), ('member', 'Member')], max_length=40)),
                ('status_label', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_ACTIVATION', 'Pending Activation'), ('SUSPENDED', 'Suspended')], default='PENDING_ACTIVATION', max_length=30)),
                ('position_label', models.CharField(blank=True, default='', max_length=80)),
                ('preferred_language', models.CharField(blank=True, default='', max_length=16)),
                ('preference_tags', models.JSONField(blank=True, default=list)),
                ('team_ids', models.JSONField(blank=True, default=list)),
                ('season_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_user_profiles',
                'indexes': [models.Index(fields=['role_label'], name='users_user__role_la_dc2d01_idx'), models.Index(fields=['status_label'], name='users_user__status__c16d7d_idx'), models.Index(fields=['organization_id', 'role_label'], name='users_user__organiz_d370de_idx')],
            },
        ),
    ]
