# Generated by Django 5.0.4 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofilemodel',
            name='users_profile_role_label_valid',
        ),
        migrations.RemoveConstraint(
            model_name='userprofilemodel',
            name='users_profile_status_label_valid',
        ),
    ]
