# Generated by Django 5.0.4 on 2026-03-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('season_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=32, null=True)),
                ('category_label', models.CharField(db_index=True, max_length=80)),
                ('status_label', models.CharField(db_index=True, default='DRAFT', max_length=20)),
                ('athlete_ids', models.JSONField(default=list)),
                ('staff_user_ids', models.JSONField(default=list)),
                ('roster_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams_team',
                'ordering': ['name'],
            },
        ),
    ]
