# Generated by Django 5.0.4 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teammodel',
            name='teams_team_status_label_valid',
        ),
        migrations.RemoveIndex(
            model_name='teammodel',
            name='teams_team_org_status_idx',
        ),
    ]
