# Generated by Django 5.0.4 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainingsessionmodel',
            name='training_session_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='trainingsessionmodel',
            name='training_session_planned_load_range',
        ),
        migrations.RemoveConstraint(
            model_name='trainingsessionmodel',
            name='training_session_intensity_target_range',
        ),
        migrations.RemoveConstraint(
            model_name='trainingsessionmodel',
            name='training_session_group_climate_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnesspostmodel',
            name='training_wellness_post_perceived_exertion_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnesspostmodel',
            name='training_wellness_post_enjoyment_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnesspostmodel',
            name='training_wellness_post_technical_learning_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnesspremodel',
            name='training_wellness_pre_readiness_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnesspremodel',
            name='training_wellness_pre_sleep_quality_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnesspremodel',
            name='training_wellness_pre_mood_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnesspremodel',
            name='training_wellness_pre_fatigue_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnesspremodel',
            name='training_wellness_pre_muscle_soreness_range',
        ),
        migrations.RemoveIndex(
            model_name='executionrecordmodel',
            name='training_exec_record_sess_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='mesocyclemodel',
            name='training_mesocycle_season_idx',
        ),
        migrations.RemoveIndex(
            model_name='mesocyclemodel',
            name='training_mesocycle_org_season_idx',
        ),
        migrations.RemoveIndex(
            model_name='microcyclemodel',
            name='training_microcycle_team_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingsessionmodel',
            name='training_session_deleted_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingsessionmodel',
            name='training_session_org_deleted_idx',
        ),
        migrations.RemoveIndex(
            model_name='wellnesspostmodel',
            name='training_wellness_post_sess_ath_idx',
        ),
        migrations.RemoveIndex(
            model_name='wellnesspremodel',
            name='training_wellness_pre_sess_ath_idx',
        ),
    ]
