# Generated by Django 5.0.4 on 2026-04-10 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_remove_trainingsessionmodel_training_session_status_valid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecordModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("session_id", models.UUIDField(db_index=True)),
                ("athlete_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("JUSTIFIED", "Justified"),
                            ("PRECONFIRMED", "Preconfirmed"),
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        max_length=32,
                        default="coach_input",
                        choices=[
                            ("coach_input", "Coach Input"),
                            ("athlete_selfcheck", "Athlete Selfcheck"),
                            ("correction", "Correction"),
                        ],
                    ),
                ),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("correction_by_user_id", models.UUIDField(null=True, blank=True)),
                ("correction_at", models.DateTimeField(null=True, blank=True)),
                ("justification_reason", models.CharField(max_length=255, blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "training_attendance_records",
                "app_label": "training",
            },
        ),
        migrations.AddIndex(
            model_name="attendancerecordmodel",
            index=models.Index(fields=["session_id", "athlete_id"], name="training_attend_sess_ath_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecordmodel",
            index=models.Index(fields=["session_id", "recorded_at"], name="training_attend_sess_rec_idx"),
        ),
    ]
