# Generated by Django 5.0.4 on 2026-04-10 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_attendance_record_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("session_id", models.UUIDField(db_index=True)),
                ("generated_by_rule", models.CharField(max_length=128)),
                (
                    "action_type",
                    models.CharField(
                        max_length=32,
                        choices=[
                            ("MODIFY_FOCUS", "Modify Focus"),
                            ("ADD_BLOCK", "Add Block"),
                            ("REMOVE_BLOCK", "Remove Block"),
                            ("ADJUST_DURATION", "Adjust Duration"),
                            ("ADD_OBJECTIVE", "Add Objective"),
                            ("ADJUST_LOAD", "Adjust Load"),
                            ("REVIEW_ATHLETE", "Review Athlete"),
                        ],
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        max_length=16,
                        db_index=True,
                        default="PENDING",
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DISMISSED", "Dismissed"),
                        ],
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        max_length=16,
                        null=True,
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                    ),
                ),
                ("generated_by_module", models.CharField(max_length=64)),
                ("coach_note", models.TextField(blank=True, default="")),
                ("dismissal_reason", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(null=True, blank=True)),
                ("resolved_by_user_id", models.UUIDField(null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "training_recommendations",
                "app_label": "training",
            },
        ),
        migrations.AddIndex(
            model_name="recommendationmodel",
            index=models.Index(fields=["session_id", "status"], name="training_reco_sess_status_idx"),
        ),
        migrations.CreateModel(
            name="AthleteIneligibilityDeclarationModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("session_id", models.UUIDField(db_index=True)),
                ("athlete_id", models.UUIDField(db_index=True)),
                ("reason_flags", models.JSONField(default=list)),
                ("reason_other", models.TextField(blank=True, default="")),
                ("acknowledged_by_coach", models.BooleanField(default=False)),
                ("coach_note", models.TextField(blank=True, default="")),
                ("declared_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "training_athlete_ineligibility_declarations",
                "app_label": "training",
            },
        ),
        migrations.AddConstraint(
            model_name="athleteineligibilitydeclarationmodel",
            constraint=models.UniqueConstraint(
                fields=["session_id", "athlete_id"],
                name="training_ineligibility_session_athlete_uniq",
            ),
        ),
    ]
