# Generated by Django 5.0.4 on 2026-04-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_training_session_execution_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trainingsessionmodel',
            name='training_session_at_id_idx',
        ),
    ]
