# Generated by Django 5.0.4 on 2026-04-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_remove_trainingsessionmodel_training_session_at_id_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnesspremodel',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
