# Generated by Django 5.0.4 on 2026-03-22 21:29

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMediaSessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_id', models.UUIDField(db_index=True)),
                ('state', models.CharField(choices=[('DRAFT', 'DRAFT'), ('CAPTURING', 'CAPTURING'), ('SYNCING', 'SYNCING'), ('TRANSCODING', 'TRANSCODING'), ('PUBLISHED', 'PUBLISHED')], db_index=True, default='DRAFT', max_length=20)),
                ('capture_mode', models.CharField(choices=[('PANORAMIC', 'PANORAMIC'), ('AUTO_FOLLOW', 'AUTO_FOLLOW'), ('MULTI_ANGLE', 'MULTI_ANGLE')], max_length=20)),
                ('retention_policy', models.CharField(choices=[('KEEP_7_DAYS', 'KEEP_7_DAYS'), ('KEEP_30_DAYS', 'KEEP_30_DAYS'), ('KEEP_90_DAYS', 'KEEP_90_DAYS'), ('ARCHIVE_S3', 'ARCHIVE_S3'), ('PUBLIC_FOREVER', 'PUBLIC_FOREVER')], default='KEEP_7_DAYS', max_length=20)),
                ('last_timecode', models.BigIntegerField(default=0)),
                ('technical_contact_user_id', models.UUIDField(blank=True, null=True)),
                ('created_by_user_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'video_match_media_sessions',
            },
        ),
        migrations.CreateModel(
            name='DistributionProfileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_label', models.CharField(max_length=80)),
                ('target_type', models.CharField(choices=[('TECHNICAL_INTERNAL', 'TECHNICAL_INTERNAL'), ('PUBLIC_CDN', 'PUBLIC_CDN'), ('BROADCAST_PARTNER', 'BROADCAST_PARTNER')], db_index=True, max_length=30)),
                ('codec_label', models.CharField(choices=[('H264', 'H264'), ('H265', 'H265'), ('VP9', 'VP9'), ('AV1', 'AV1')], max_length=10)),
                ('bitrate', models.IntegerField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='video.matchmediasessionmodel')),
            ],
            options={
                'db_table': 'video_distribution_profiles',
            },
        ),
        migrations.CreateModel(
            name='ClipDefinitionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_timecode', models.BigIntegerField()),
                ('to_timecode', models.BigIntegerField()),
                ('scout_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('zone_label', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('athlete_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('context_label', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='video.matchmediasessionmodel')),
            ],
            options={
                'db_table': 'video_clip_definitions',
            },
        ),
        migrations.CreateModel(
            name='MediaSegmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timecode_logical', models.BigIntegerField(db_index=True)),
                ('timecode_label', models.CharField(max_length=60)),
                ('state', models.CharField(choices=[('OPEN', 'OPEN'), ('FINALIZED', 'FINALIZED')], db_index=True, default='OPEN', max_length=20)),
                ('codec_label', models.CharField(blank=True, max_length=60, null=True)),
                ('bitrate', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('source_edge_node_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='video.matchmediasessionmodel')),
            ],
            options={
                'db_table': 'video_media_segments',
                'unique_together': {('session', 'timecode_logical')},
            },
        ),
    ]
