# Generated by Django 5.0.4 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='distributionprofilemodel',
            name='video_distribution_target_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='distributionprofilemodel',
            name='video_distribution_codec_label_valid',
        ),
        migrations.RemoveConstraint(
            model_name='matchmediasessionmodel',
            name='video_session_state_valid',
        ),
        migrations.RemoveConstraint(
            model_name='matchmediasessionmodel',
            name='video_session_capture_mode_valid',
        ),
        migrations.RemoveConstraint(
            model_name='matchmediasessionmodel',
            name='video_session_retention_policy_valid',
        ),
        migrations.RemoveConstraint(
            model_name='mediasegmentmodel',
            name='video_segment_state_valid',
        ),
    ]
