# Generated by Django 5.0.4 on 2026-03-22 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('athlete_user_id', models.UUIDField(db_index=True)),
                ('team_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('record_date', models.DateField(db_index=True)),
                ('record_label', models.CharField(max_length=120)),
                ('assessment_summary', models.TextField(blank=True, max_length=1000, null=True)),
                ('restriction_summary', models.TextField(blank=True, max_length=1000, null=True)),
                ('return_to_training_authorized', models.BooleanField(blank=True, null=True)),
                ('return_to_play_authorized', models.BooleanField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medical_record',
                'ordering': ['-record_date'],
                'indexes': [models.Index(fields=['athlete_user_id', 'record_date'], name='medical_rec_athlete_a2a92c_idx')],
            },
        ),
    ]
