# Generated by Django 5.0.4 on 2026-04-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicalrecordmodel',
            name='medical_record_label_nonempty',
        ),
    ]
