"""Tests for scripts/compile/compile_contracts.py — contracts compiler invariants."""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parent.parent.parent

MODULES = [
    "ai_ingestion", "analytics", "audit", "competitions", "exercises",
    "identity_access", "matches", "medical", "notifications", "reports",
    "scout", "seasons", "teams", "training", "users", "video", "wellness",
]


def _load_paths_yaml(module: str) -> dict:
    dest = ROOT / "contracts/openapi/paths" / f"{module}.yaml"
    return yaml.safe_load(dest.read_text()) or {}


def _load_source_yaml(module: str) -> dict:
    src = ROOT / "docs/hbtrack/modulos" / module / "graph/openapi_paths.yaml"
    text = src.read_text()
    # Strip comment header
    lines = text.splitlines(keepends=True)
    start = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            start = i
            break
    return yaml.safe_load("".join(lines[start:])) or {}


@pytest.mark.parametrize("module", MODULES)
def test_source_master_exists(module: str) -> None:
    """Each module must have openapi_paths.yaml source master in graph/."""
    src = ROOT / "docs/hbtrack/modulos" / module / "graph/openapi_paths.yaml"
    assert src.exists(), f"Missing source master: {src}"


@pytest.mark.parametrize("module", MODULES)
def test_generated_file_has_generated_header(module: str) -> None:
    """contracts/openapi/paths/<module>.yaml must have GENERATED header."""
    dest = ROOT / "contracts/openapi/paths" / f"{module}.yaml"
    assert dest.exists(), f"Missing generated file: {dest}"
    content = dest.read_text()
    assert "GENERATED by scripts/compile/compile_contracts.py" in content, (
        f"{dest.name} missing GENERATED header — run: python3 scripts/compile/compile_contracts.py --all"
    )


@pytest.mark.parametrize("module", MODULES)
def test_semantic_parity_source_vs_generated(module: str) -> None:
    """YAML content must be semantically identical between source master and generated file."""
    source_data = _load_source_yaml(module)
    generated_data = _load_paths_yaml(module)
    assert source_data == generated_data, (
        f"Semantic mismatch for {module} — re-run: python3 scripts/compile/compile_contracts.py --module {module}"
    )


def test_compiler_produces_valid_openapi_for_all_modules() -> None:
    """Compiler --check mode must pass for all 17 modules without errors."""
    result = subprocess.run(
        [sys.executable, "scripts/compile/compile_contracts.py", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"compile_contracts.py --check failed:\n{result.stdout}\n{result.stderr}"
    )
    assert "RESULT: PASS" in result.stdout


def test_compiler_is_deterministic() -> None:
    """Running compile --all twice must produce identical output."""
    import hashlib

    def hash_all_generated() -> dict[str, str]:
        hashes = {}
        for module in MODULES:
            dest = ROOT / "contracts/openapi/paths" / f"{module}.yaml"
            content = dest.read_text()
            hashes[module] = hashlib.sha256(content.encode()).hexdigest()
        return hashes

    # First compile
    result1 = subprocess.run(
        [sys.executable, "scripts/compile/compile_contracts.py", "--all"],
        cwd=ROOT, capture_output=True, text=True
    )
    assert result1.returncode == 0
    hashes_1 = hash_all_generated()

    # Second compile
    result2 = subprocess.run(
        [sys.executable, "scripts/compile/compile_contracts.py", "--all"],
        cwd=ROOT, capture_output=True, text=True
    )
    assert result2.returncode == 0
    hashes_2 = hash_all_generated()

    assert hashes_1 == hashes_2, "Compiler is not deterministic — output differs between runs"


def test_all_source_masters_are_valid_yaml() -> None:
    """All 17 openapi_paths.yaml source masters must be valid YAML."""
    errors = []
    for module in MODULES:
        src = ROOT / "docs/hbtrack/modulos" / module / "graph/openapi_paths.yaml"
        try:
            data = _load_source_yaml(module)
            if not data:
                errors.append(f"{module}: parsed as empty/None")
        except Exception as e:
            errors.append(f"{module}: {e}")
    assert not errors, f"YAML parse errors:\n" + "\n".join(errors)


def test_sync_manifest_has_openapi_paths_rules() -> None:
    """SYNC_MANIFEST.yaml must contain <MODULE>_OPENAPI_PATHS_SYNC for all 17 modules."""
    sync_manifest = ROOT / "docs/_canon/SYNC_MANIFEST.yaml"
    content = sync_manifest.read_text()
    missing = [m for m in MODULES if f"{m.upper()}_OPENAPI_PATHS_SYNC" not in content]
    assert not missing, (
        f"Missing OPENAPI_PATHS_SYNC rules in SYNC_MANIFEST for: {missing}"
    )


def test_source_authority_graph_marks_paths_as_derived() -> None:
    """SOURCE_AUTHORITY_GRAPH.yaml must classify contracts/openapi/paths/ as derived."""
    sag = ROOT / "docs/_canon/SOURCE_AUTHORITY_GRAPH.yaml"
    content = sag.read_text()
    assert "openapi_paths_derived" in content, (
        "SOURCE_AUTHORITY_GRAPH.yaml missing 'openapi_paths_derived' entry — "
        "contracts/openapi/paths/*.yaml must be classified as derived artifacts"
    )
    assert "compile_contracts.py" in content, (
        "SOURCE_AUTHORITY_GRAPH.yaml 'openapi_paths_derived' must reference compile_contracts.py as generator"
    )
