# Generated by Django 5.0.4 on 2026-03-22 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessEntryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('athlete_user_id', models.UUIDField(db_index=True)),
                ('training_session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('questionnaire_date', models.DateField(db_index=True)),
                ('questionnaire_label', models.CharField(blank=True, max_length=80, null=True)),
                ('readiness_score', models.SmallIntegerField()),
                ('fatigue_score', models.SmallIntegerField(blank=True, null=True)),
                ('pain_score', models.SmallIntegerField(blank=True, null=True)),
                ('recovery_score', models.SmallIntegerField(blank=True, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wellness_entry',
                'ordering': ['-questionnaire_date'],
                'indexes': [models.Index(fields=['athlete_user_id', 'questionnaire_date'], name='wellness_en_athlete_a89add_idx')],
            },
        ),
    ]
