# Generated by Django 5.0.4 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wellnessentrymodel',
            name='wellness_entry_readiness_score_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnessentrymodel',
            name='wellness_entry_fatigue_score_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnessentrymodel',
            name='wellness_entry_pain_score_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnessentrymodel',
            name='wellness_entry_recovery_score_range',
        ),
        migrations.RemoveConstraint(
            model_name='wellnessentrymodel',
            name='wellness_entry_sleep_hours_range',
        ),
    ]
