#!/usr/bin/env python3
"""
Archive Task Script - Creates execution_tasks artifacts structure
Part of ARCH-DOCS-ARTIFACTS-002 implementation

Purpose: Create artifacts/<TASK_ID>/ and write summary.json + placeholders
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
import subprocess


def get_git_commit_hash():
    """Get current git commit hash (short)"""
    try:
        result = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], 
                              capture_output=True, text=True, check=True)
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def create_artifacts_directory(task_id: str, base_path: Path) -> Path:
    """Create artifacts directory for task"""
    artifacts_dir = base_path / "docs" / "execution_tasks" / "artifacts" / task_id
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    return artifacts_dir


def create_summary_json(task_id: str, status: str, description: str, 
                       timestamp: str, commit: str, artifacts_dir: Path):
    """Create summary.json file (Strict-Minimal 5 keys)"""
    summary_data = {
        "task_id": task_id,
        "status": status,
        "timestamp": timestamp,
        "commit_hash": commit,
        "brief_description": description
    }
    
    summary_file = artifacts_dir / "summary.json"
    with open(summary_file, 'w', encoding='utf-8', newline='\n') as f:
    
    return summary_file


def create_placeholder_files(task_id: str, artifacts_dir: Path, timestamp: str, log_file: str = None):
    """Create placeholder execution_log.txt and evidence_index.md"""

    # execution_log.txt
    log_content = f"""=== {task_id} Execution Log ===
Timestamp: {timestamp}
Status: Archived via archive_task.py

COMMANDS EXECUTED:
1. archive_task.py --task-id {task_id}
   EXIT_CODE: 0
   OUTPUT: Artifacts directory created

=== END LOG ===
"""

    if log_file and Path(log_file).exists():
        # Copy actual log file if provided
        with open(log_file, 'r', encoding='utf-8') as f:
            log_content = f.read()

    log_path = artifacts_dir / "execution_log.txt"
    with open(log_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(log_content)

    # evidence_index.md
    evidence_content = f"""# Evidence Index - {task_id}

**Task ID:** {task_id}
**Status:** Archived
**Timestamp:** {timestamp}

## Artifacts Generated

| File | Path | Purpose |
|------|------|---------|
| summary.json | docs/execution_tasks/artifacts/{task_id}/summary.json | Machine-readable task metadata |
| execution_log.txt | docs/execution_tasks/artifacts/{task_id}/execution_log.txt | Command execution log |
| evidence_index.md | docs/execution_tasks/artifacts/{task_id}/evidence_index.md | This file - evidence catalog |

## Evidence Packs

No evidence packs created during archival.

---

**Generated by:** scripts/archive_task.py
"""
    
    evidence_path = artifacts_dir / "evidence_index.md"
    with open(evidence_path, 'w', encoding='utf-8', newline='\n') as f:
    
    return log_path, evidence_path


def validate_summary_schema(summary_file: Path) -> bool:
    """Validate that summary.json follows required strict-minimal schema"""
    try:
        with open(summary_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        required_keys = ["task_id", "status", "timestamp", "commit_hash", "brief_description"]
        
        # Verify all required keys are present
        for key in required_keys:
            if key not in data:
                print(f"ERROR: Missing required key '{key}' in summary.json", file=sys.stderr)
                return False
        
        # Verify NO extra keys (Strict-Minimal)
        if len(data) > len(required_keys):
            extra_keys = set(data.keys()) - set(required_keys)
            print(f"ERROR: Extra keys found in strict-minimal summary.json: {extra_keys}", file=sys.stderr)
            return False

        # Validate status enum
        if data["status"] not in ["PASS", "FAIL", "DRIFT"]:
            print(f"ERROR: Invalid status '{data['status']}'. Must be PASS|FAIL|DRIFT", file=sys.stderr)
            return False
        
        # Validate brief_description length
        if len(data["brief_description"]) > 120:
            print(f"ERROR: brief_description too long ({len(data['brief_description'])} chars, max 120)", file=sys.stderr)
            return False
        
        return True
        
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in summary.json: {e}", file=sys.stderr)
        return False
    except Exception as e:
        print(f"ERROR: Validation failed: {e}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(description='Archive execution task artifacts')
    parser.add_argument('--task-id', required=True, help='Task ID (e.g., EXEC-AUTH-001)')
    parser.add_argument('--status', required=True, choices=['PASS', 'FAIL', 'DRIFT'],
                       help='Task execution status')
    parser.add_argument('--description', required=True, help='Brief description (max 120 chars)')
    parser.add_argument('--timestamp', help='ISO8601 timestamp (default: now UTC)')
    parser.add_argument('--commit', help='Git commit hash (default: current HEAD)')
    parser.add_argument('--log-file', help='Path to execution log file to copy')
    
    args = parser.parse_args()
    
    # Validate inputs
    if len(args.description) > 120:
        print(f"ERROR: Description too long ({len(args.description)} chars, max 120)", file=sys.stderr)
        return 2
    
    # Set defaults
    timestamp = args.timestamp or datetime.now(timezone.utc).isoformat()
    commit = args.commit or get_git_commit_hash()
    
    try:
        # Get repo root
        repo_root = Path.cwd()
        
        # Create artifacts directory
        artifacts_dir = create_artifacts_directory(args.task_id, repo_root)
        print(f"Created artifacts directory: {artifacts_dir}")
        
        # Create summary.json
        summary_file = create_summary_json(
            args.task_id, args.status, args.description, timestamp, commit, artifacts_dir)
        print(f"Created summary.json: {summary_file}")
        
        # Create placeholder files
        log_file, evidence_file = create_placeholder_files(args.task_id, artifacts_dir, timestamp, args.log_file)
        
        print(f"SUCCESS: Task {args.task_id} archived successfully")
        return 0
        
    except Exception as e:
        print(f"ERROR: Runtime error: {e}", file=sys.stderr)
        return 3


if __name__ == "__main__":
    sys.exit(main())