#!/usr/bin/env python3
"""
Refresh Task Index Script - Generate INDEX.md and TIMELINE.md
Part of ARCH-DOCS-ARTIFACTS-002 implementation

Purpose: Generate INDEX.md and TIMELINE.md deterministically from event.json or summary.json
"""

import json
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional


def find_task_directories(base_path: Path) -> List[Path]:
    """Find all task directories in artifacts/"""
    artifacts_path = base_path / "docs" / "execution_tasks" / "artifacts"
    
    if not artifacts_path.exists():
        return []
    
    task_dirs = []
    for item in artifacts_path.iterdir():
        if item.is_dir() and not item.name.startswith('.'):
            task_dirs.append(item)
    
    return sorted(task_dirs)


def load_task_metadata(task_dir: Path) -> Optional[Dict]:
    """Load task metadata from event.json (preferred) or summary.json (fallback)"""
    
    # Try event.json first (canonical)
    event_file = task_dir / "event.json"
    if event_file.exists():
        try:
            with open(event_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                
            # Normalize event.json format for index generation
            return {
                "task_id": data.get("task_id"),
                "status": data.get("status", "UNKNOWN"),
                "timestamp": data.get("timestamp_end") or data.get("timestamp_start") or data.get("timestamp"),
                "commit_hash": extract_commit_from_artifacts(data.get("artifacts", [])),
                "brief_description": data.get("short_title") or data.get("notes_short", ""),
                "source": "event.json"
            }
        except (json.JSONDecodeError, KeyError, TypeError) as e:
            print(f"WARNING: Invalid event.json in {task_dir.name}: {e}", file=sys.stderr)
    
    # Fallback to summary.json
    summary_file = task_dir / "summary.json"
    if summary_file.exists():
        try:
            with open(summary_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                
            return {
                "task_id": data.get("task_id"),
                "status": data.get("status", "UNKNOWN"),
                "timestamp": data.get("timestamp"),
                "commit_hash": data.get("commit_hash", "unknown"),
                "brief_description": data.get("brief_description", ""),
                "source": "summary.json"
            }
        except (json.JSONDecodeError, KeyError, TypeError) as e:
            print(f"WARNING: Invalid summary.json in {task_dir.name}: {e}", file=sys.stderr)
    
    print(f"WARNING: No valid metadata found in {task_dir.name}", file=sys.stderr)
    return None


def extract_commit_from_artifacts(artifacts: List[str]) -> str:
    """Try to extract commit hash from artifacts paths or git references"""
    # Simple implementation - look for git_state.txt or similar
    for artifact in artifacts:
        if 'git_state' in artifact.lower():
            # Could extract from git_state.txt if needed
            pass
    return "unknown"


def validate_task_metadata(metadata: Dict) -> bool:
    """Validate that task metadata is complete"""
    required_fields = ["task_id", "status", "timestamp", "commit_hash", "brief_description"]
    
    for field in required_fields:
        if not metadata.get(field):
            return False
    
    # Check for duplicate task_id (caller should handle)
    return True


def normalize_timestamp(timestamp_str: str) -> str:
    """Normalize timestamp to consistent format"""
    try:
        # Parse and reformat to ensure consistent format
        if timestamp_str:
            # Handle various ISO formats
            dt = datetime.fromisoformat(timestamp_str.replace('Z', '+00:00'))
            return dt.strftime('%Y-%m-%dT%H:%M:%S') + 'Z'
    except (ValueError, TypeError):
        return "1970-01-01T00:00:00Z"
    
    return "1970-01-01T00:00:00Z"


def generate_index_md(tasks: List[Dict], output_path: Path):
    """Generate INDEX.md sorted by task_id ascending (1 line per task)"""
    
    # Sort by task_id ascending
    sorted_tasks = sorted(tasks, key=lambda t: t["task_id"])
    
    content = """# Execution Tasks Index

<!-- AUTO-GENERATED. Source: docs/execution_tasks/artifacts/*/(event.json|summary.json) -->
<!-- Generated by: scripts/refresh_task_index.py -->

## Task Index (Alphabetical)

"""
    
    for task in sorted_tasks:
        commit_short = task["commit_hash"][:7] if len(task["commit_hash"]) > 7 else task["commit_hash"]
        content += f"- {task['task_id']} | {task['status']} | {task['timestamp']} | {commit_short} | {task['brief_description']}\n"
    
    content += f"\n**Total Tasks:** {len(sorted_tasks)}\n"
    content += "\n---\n\n"
    content += "**Note:** This file is auto-generated. Do not edit manually.\n"
    content += "To regenerate: `python scripts/refresh_task_index.py`\n"
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)


def generate_timeline_md(tasks: List[Dict], output_path: Path):
    """Generate TIMELINE.md sorted by timestamp ascending (1 line per task)"""
    
    # Sort by timestamp ascending, then task_id ascending for determinism
    sorted_tasks = sorted(tasks, key=lambda t: (normalize_timestamp(t["timestamp"]), t["task_id"]))
    
    content = """# Execution Tasks Timeline

<!-- AUTO-GENERATED. Source: docs/execution_tasks/artifacts/*/(event.json|summary.json) -->
<!-- Generated by: scripts/refresh_task_index.py -->

## Chronological Timeline

"""
    
    for task in sorted_tasks:
        commit_short = task["commit_hash"][:7] if len(task["commit_hash"]) > 7 else task["commit_hash"]
        content += f"- {task['timestamp']} | {task['task_id']} | {task['status']} | {commit_short} | {task['brief_description']}\n"
    
    content += f"\n**Total Tasks:** {len(sorted_tasks)}\n"
    content += "\n---\n\n"
    content += "**Note:** This file is auto-generated. Do not edit manually.\n"
    content += "To regenerate: `python scripts/refresh_task_index.py`\n"
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)


def main():
    try:
        repo_root = Path.cwd()
        
        # Find task directories
        task_dirs = find_task_directories(repo_root)
        print(f"Found {len(task_dirs)} task directories")
        
        if not task_dirs:
            print("No task directories found. Creating empty indices.")
        
        # Load metadata for all tasks
        tasks = []
        task_ids_seen = set()
        
        for task_dir in task_dirs:
            metadata = load_task_metadata(task_dir)
            if metadata and validate_task_metadata(metadata):
                
                # Check for duplicate task_id
                if metadata["task_id"] in task_ids_seen:
                    print(f"ERROR: Duplicate task_id '{metadata['task_id']}' found", file=sys.stderr)
                    return 2
                
                task_ids_seen.add(metadata["task_id"])
                tasks.append(metadata)
                print(f"Loaded: {metadata['task_id']} ({metadata['source']})")
            else:
                print(f"SKIP: {task_dir.name} (invalid or missing metadata)")
        
        print(f"Loaded {len(tasks)} valid tasks")
        
        # Generate indices
        execution_tasks_dir = repo_root / "docs" / "execution_tasks"
        index_path = execution_tasks_dir / "INDEX.md"
        timeline_path = execution_tasks_dir / "TIMELINE.md"
        
        generate_index_md(tasks, index_path)
        print(f"Generated INDEX.md: {index_path}")
        
        generate_timeline_md(tasks, timeline_path)
        print(f"Generated TIMELINE.md: {timeline_path}")
        
        print("SUCCESS: Index generation completed")
        return 0
        
    except Exception as e:
        print(f"ERROR: Runtime error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return 3


if __name__ == "__main__":
    sys.exit(main())