# Generated by Django 5.0.4 on 2026-03-22 23:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJobModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_label', models.CharField(max_length=120)),
                ('ingestion_mode', models.CharField(max_length=40)),
                ('payload_schema_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('mapping_profile', models.CharField(blank=True, max_length=120, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('execution_binding_label', models.CharField(blank=True, max_length=80, null=True)),
                ('status_label', models.CharField(default='queued', max_length=20)),
                ('received_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('origin_job_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingestion_job',
                'ordering': ['-received_at'],
            },
        ),
    ]
