# Generated by Django 5.0.4 on 2026-03-22 22:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competition_id', models.UUIDField(db_index=True)),
                ('home_team_id', models.UUIDField(db_index=True)),
                ('away_team_id', models.UUIDField(db_index=True)),
                ('status_label', models.CharField(db_index=True, default='SCHEDULED', max_length=20)),
                ('venue_label', models.CharField(blank=True, max_length=200, null=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('referee_names', models.JSONField(blank=True, default=list)),
                ('lineup_user_ids', models.JSONField(blank=True, default=list)),
                ('official_incident_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'match',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['competition_id', 'scheduled_at'], name='match_competi_360dcb_idx')],
            },
        ),
    ]
