# Generated by Django 5.0.4 on 2026-03-22 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshotModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(max_length=50)),
                ('source_module_labels', models.JSONField(default=list)),
                ('time_window_label', models.CharField(blank=True, max_length=80, null=True)),
                ('granularity_label', models.CharField(blank=True, max_length=40, null=True)),
                ('filter_summary', models.TextField(blank=True, max_length=500, null=True)),
                ('projection_key', models.CharField(blank=True, max_length=80, null=True)),
                ('refresh_mode_label', models.CharField(blank=True, max_length=40, null=True)),
                ('computed_at', models.DateTimeField()),
                ('created_by_user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_snapshot',
                'ordering': ['-computed_at'],
            },
        ),
    ]
