# Generated by Django 5.0.4 on 2026-04-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analyticssnapshotmodel',
            name='analytics_snapshot_metric_key_nonempty',
        ),
    ]
