# Generated by Django 5.0.4 on 2026-03-22 23:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_user_id', models.UUIDField()),
                ('action', models.CharField(max_length=120)),
                ('occurred_at', models.DateTimeField()),
                ('target_resource_id', models.UUIDField(blank=True, null=True)),
                ('target_resource_type', models.CharField(blank=True, max_length=80, null=True)),
                ('outcome_label', models.CharField(blank=True, max_length=40, null=True)),
                ('origin_label', models.CharField(blank=True, max_length=80, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('before_summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('after_summary', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'audit_entry',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
