# Generated by Django 5.0.4 on 2026-04-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_audit_append_only_trigger'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditentrymodel',
            name='audit_entry_action_nonempty',
        ),
    ]
