"""
Contrato de surface pública do módulo training.

Falha se qualquer símbolo exportado que é consumido por `config/urls.py` ou por
`src/training/api.py` deixar de existir no path original. Protege contra regressão
silenciosa durante a refatoração estrutural (Fases 1-6).

A lista PUBLIC_SURFACE foi gerada na Fase 0.5 por introspecção dos imports reais
de api.py e urls.py. Remover um símbolo daqui exige migração explícita dos call
sites e documentação de depreciação.
"""
from __future__ import annotations

import importlib

import pytest


PUBLIC_SURFACE: dict[str, list[str]] = {
    "training.api": ["router"],
    "training.models": [
        "AttendanceRecordModel",
        "AthleteIneligibilityDeclarationModel",
        "AttentionQueueItemModel",
        "ExecutionRecordModel",
        "FeedbackThreadModel",
        "MesocycleModel",
        "MicrocycleModel",
        "RecommendationModel",
        "SessionBlockModel",
        "SessionObjectiveModel",
        "TrainingSessionModel",
        "WellnessPostModel",
        "WellnessPreModel",
    ],
    "training.domain.entities": [
        "TrainingSessionStatus",
    ],
    "training.domain.rules": [
        "AttentionQueueConflict",
        "AttentionQueueItemNotFound",
        "DuplicateWellnessEntry",
        "ElasticSumRuleViolation",
        "ExecutionRecordNotFound",
        "FeedbackThreadNotFound",
        "IneligibilityDeclarationNotFound",
        "InsufficientPrivilege",
        "InvalidStatusTransition",
        "MesocycleNotFound",
        "MicrocycleNotFound",
        "RecommendationConflict",
        "RecommendationNotFound",
        "RoleLabel",
        "SessionBlockNotFound",
        "SessionNotMutable",
        "TrainingSessionNotFound",
        "WellnessEntryNotFound",
        "WellnessWindowClosed",
    ],
    "training.infrastructure.repository": [
        "AthleteIneligibilityDeclarationRepository",
        "AttendanceRepository",
        "AttentionQueueRepository",
        "ExecutionRecordRepository",
        "FeedbackThreadRepository",
        "MesocycleRepository",
        "MicrocycleRepository",
        "RecommendationRepository",
        "SessionBlockRepository",
        "SessionObjectiveRepository",
        "TrainingSessionRepository",
        "WellnessPostRepository",
        "WellnessPreRepository",
    ],
    "training.application.use_cases": [
        "AcceptRecommendationInput",
        "AcceptRecommendationUseCase",
        "AddSessionBlockInput",
        "AddSessionBlockUseCase",
        "CloseFeedbackThreadInput",
        "CloseFeedbackThreadUseCase",
        "CreateExecutionRecordInput",
        "CreateExecutionRecordUseCase",
        "CreateFeedbackThreadInput",
        "CreateFeedbackThreadUseCase",
        "CreateMesocycleInput",
        "CreateMesocycleUseCase",
        "CreateMicrocycleInput",
        "CreateMicrocycleUseCase",
        "CreateSessionObjectiveInput",
        "CreateSessionObjectiveUseCase",
        "CreateTrainingSessionInput",
        "CreateTrainingSessionUseCase",
        "DeleteSessionBlockInput",
        "DeleteSessionBlockUseCase",
        "DeleteTrainingSessionInput",
        "DeleteTrainingSessionUseCase",
        "DismissAttentionQueueItemInput",
        "DismissAttentionQueueItemUseCase",
        "DismissRecommendationInput",
        "DismissRecommendationUseCase",
        "EscalateAttentionQueueItemInput",
        "EscalateAttentionQueueItemUseCase",
        "GetExecutionRecordInput",
        "GetExecutionRecordUseCase",
        "GetIneligibilityStatusInput",
        "GetIneligibilityStatusUseCase",
        "GetLoadChartInput",
        "GetLoadChartUseCase",
        "GetMesocycleInput",
        "GetMesocycleUseCase",
        "GetMicrocycleInput",
        "GetMicrocycleUseCase",
        "GetSessionBlockInput",
        "GetSessionBlockUseCase",
        "GetTrainingSessionInput",
        "GetTrainingSessionUseCase",
        "GetWellnessPostInput",
        "GetWellnessPostUseCase",
        "GetWellnessPreInput",
        "GetWellnessPreUseCase",
        "ListAttentionQueueItemsInput",
        "ListAttentionQueueItemsUseCase",
        "ListChatMessagesInput",
        "ListChatMessagesUseCase",
        "ListExecutionRecordsInput",
        "ListExecutionRecordsUseCase",
        "ListFeedbackThreadsInput",
        "ListFeedbackThreadsUseCase",
        "ListMesocyclesInput",
        "ListMesocyclesUseCase",
        "ListMicrocyclesInput",
        "ListMicrocyclesUseCase",
        "ListRecommendationsInput",
        "ListRecommendationsUseCase",
        "ListSessionAttendanceInput",
        "ListSessionAttendanceUseCase",
        "ListSessionBlocksInput",
        "ListSessionBlocksUseCase",
        "ListSessionObjectivesInput",
        "ListSessionObjectivesUseCase",
        "ListTrainingSessionsInput",
        "ListTrainingSessionsUseCase",
        "RecordSessionAttendanceInput",
        "RecordSessionAttendanceUseCase",
        "ReorderSessionBlocksInput",
        "ReorderSessionBlocksUseCase",
        "ResolveAttentionQueueItemInput",
        "ResolveAttentionQueueItemUseCase",
        "SubmitIneligibilityDeclarationInput",
        "SubmitIneligibilityDeclarationUseCase",
        "SubmitTrainingSuggestionInput",
        "SubmitTrainingSuggestionUseCase",
        "SubmitWellnessPostInput",
        "SubmitWellnessPostUseCase",
        "SubmitWellnessPreInput",
        "SubmitWellnessPreUseCase",
        "TransitionTrainingSessionInput",
        "TransitionTrainingSessionUseCase",
        "UpdateMesocycleInput",
        "UpdateMesocycleUseCase",
        "UpdateMicrocycleInput",
        "UpdateMicrocycleUseCase",
        "UpdateSessionBlockInput",
        "UpdateSessionBlockUseCase",
        "UpdateTrainingSessionInput",
        "UpdateTrainingSessionUseCase",
        "UpdateWellnessPostInput",
        "UpdateWellnessPostUseCase",
        "UpdateWellnessPreInput",
        "UpdateWellnessPreUseCase",
    ],
    "training.schemas": [
        "AcceptRecommendationIn",
        "AddSessionBlockIn",
        "AthleteIneligibilityDeclarationOut",
        "AttendanceListOut",
        "AttendanceRecordOut",
        "AttentionQueueItemOut",
        "AttentionQueueListOut",
        "CloseFeedbackThreadIn",
        "CreateExecutionRecordIn",
        "CreateFeedbackThreadIn",
        "CreateMesocycleIn",
        "CreateMicrocycleIn",
        "CreateSessionObjectiveIn",
        "CreateTrainingSessionIn",
        "DismissAttentionQueueItemIn",
        "DismissRecommendationIn",
        "ErrorOut",
        "EscalateAttentionQueueItemIn",
        "ExecutionRecordListOut",
        "ExecutionRecordOut",
        "FeedbackThreadListOut",
        "FeedbackThreadOut",
        "LoadChartEntryOut",
        "LoadChartOut",
        "MesocycleListOut",
        "MesocycleOut",
        "MicrocycleListOut",
        "MicrocycleOut",
        "RecommendationListOut",
        "RecommendationOut",
        "RecordSessionAttendanceIn",
        "ReorderSessionBlocksIn",
        "ResolveAttentionQueueItemIn",
        "SessionBlockListOut",
        "SessionBlockOut",
        "SessionObjectiveListOut",
        "SessionObjectiveOut",
        "SubmitIneligibilityDeclarationIn",
        "SubmitTrainingSuggestionIn",
        "SubmitWellnessPostIn",
        "SubmitWellnessPreIn",
        "TrainingSessionListOut",
        "TrainingSessionOut",
        "TransitionOut",
        "UpdateMesocycleIn",
        "UpdateMicrocycleIn",
        "UpdateSessionBlockIn",
        "UpdateTrainingSessionIn",
        "UpdateWellnessPostIn",
        "UpdateWellnessPreIn",
        "WellnessPostOut",
        "WellnessPreOut",
    ],
}


@pytest.mark.parametrize("module_path,symbols", list(PUBLIC_SURFACE.items()))
def test_public_symbols_are_importable(module_path: str, symbols: list[str]) -> None:
    module = importlib.import_module(module_path)
    missing = [sym for sym in symbols if not hasattr(module, sym)]
    assert not missing, (
        f"{module_path} perdeu símbolos durante refatoração: {missing}. "
        f"Se intencional, atualizar PUBLIC_SURFACE e migrar consumidores."
    )


def test_training_api_router_is_ninja_router() -> None:
    from ninja import Router

    from training.api import router

    assert isinstance(router, Router), (
        "training.api.router deve ser instância de ninja.Router — "
        "config/urls.py depende disso."
    )
